2023-04-03 22:07:52,317 ERROR [logging_use.py(<module>:47)] - xxx是一条错误日志，错误码是：20001
